name: genreGenius
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - numba
  - gensim
  - nltk
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - hdbscan
  - jupyter
  - nb_conda
  - umap-learn
